### ISSUE TITLE
Data type conversion bettween python bool and pytubes Bool

### ISSUE THREAD

**Issue by qzshucsz** [stestagg/pytubes#22]
Hi, i need to add filter function in pytubes skip_if function. Specifically, it is complicated lambda expression which make more judgements than 'lambda x: x.is_blank()'. For example, for string list ['apple','banana','cherry'], i want to get strings which does not contain  character 'a'. With the help of pytubes, i write some code clips like:
(Each( ['apple','banana',''])
.enumerate()
.skip_if(lambda x: contain_a(x))
)
here, contain_a is  function which  return python's  bool value represents whether the string contains character.
contain_a(x):
     if 'a' in x:
        return True
     else:
        return False

However, i got an error "TypeError: Argument 'conditional' has incorrect type (expected ctubes.Tube, got bool)".  It means skip_if function of pytubes is not compatible with python bool, just compatible with tubes.Bool. Is pytubes provides conversion between python bool and tubes.Bool ?

**Comment by stestagg** [comment]
The problem here is that you can't (currently) include python functions/filter like that in a tube.
The lambda function allows you to define a filter `Tube` (a tube that returns bool values), not a filter function (a function that returns a bool value)

I can see how this would be useful, but it's also a bit 'dangerous' as it'll kill performance. (For most workloads, pytubes doesn't actually deal with python objects directly, so if you want to include a python function, it'll have to do lots of conversions to/from python objects which is very slow)

As a workaround, you can achieve this by doing the following:

```
>>> src = ['apple','banana','cherry']
>>> step1 = tubes.Each(src)...
>>> filtered = (fruit for fruit in step1 if 'a' in fruit)
>>> step2 = tubes.Each(filtered)...
```

Because this is all lazy evaluated, it's not too much slower than the proposed solution, even if the code is a bit more messy.

To show this, let's say you want to square the first 10,000 numbers, but pytubes doesn't support squaring directly:

```
>>> counter = tubes.Count()   # tubes.Count() never stops, it's equivalent to itertools.count()
>>> complex_fn = lambda x: x**2  # out 'complex' function just squares the value
>>> squares = (complex_fn(x) for x in counter) # create a generator that calls our function for each item
>>> first_10k = tubes.Each(squares).first(10_000)
>>> print(list(first_10k))
[1, 4, 9, 16, ...]
```

If you really need to do this within a skip_if() clause, then it is still possible, but even messier code:

```
complex_fn = lambda x: 'a' in x
list(tubes.Each(src).skip_unless(lambda t: tubes.Each(complex_fn(f) for f in t).to(bool)))
['apple', 'banana']
```

**Comment by qzshucsz** [comment]
Thank you for your patient and detailed reply. Conversion between python object and pytubes object would reduce performance indeed. The examples your show above inspire me greatly. Hope you can add more  examples in the document of pytubes.
